add eda
swiggy123/npr_mc2 pull request #14
Opened 2024-01-03 19:42 UTC by swiggy123

2024-01-03 22:02 UTC, florinbarbisch requested changes

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "plt.ylabel('Wie oft die Anzahl vorkommt')\n",
Statt `Wie oft die Anzahl vorkommt` wäre für mich `Wie viele Paragraphen die gleiche Anzahl an Fragen haben`

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "Die Texte haben eine sehr stark unterschiedliche Anzahl von Fragen und Antworten. Dies könnte bei den Texten, welche wenige Fragen und Antworten haben, zu Overfitting führen."
Mir ist nicht direkt klar wieso das zu Overfitting führen könnte. Kannst du da elaborieren?

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "print(f\"Es gibt {sum(np.array(qa) - np.array(qa_set))} identische Fragen und Antworten von {sum(np.array(qa) != np.array(qa_set))} Texten\")"
Würde es so schreiben: 

> Es gibt 78 identische Fragen und Antworten ~von~ _in_ 71 Texten

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "Identische Fragen und Antworten könnte zu Overfitting führen. Da es nicht alzu viele sind, werden sie im bestehenden Datensatz gelassen. In einem weiteren Schritt könnte untersucht werden, ob si
Würde statt overfitting schreiben: 

> Identische Fragen und Antworten könnten das Modell dazu bringen, Fragen beim generieren zu wiederholen.

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "axs[0].bar(unique_numbers, counts, align='center', alpha=0.7)\n",
Für mich sind die Titel und Achsenbeschriftungen nicht einfach verständlich. Würde mehr in folgende Richtung schreiben:
- mehrfachen durch gleichen ersetzen 
  - Anzahl mehrfache Fragen pro Text => Anzahl gleichenFragen pro Text
- Wie oft die Fragen vorkommen würde ich durch 'Anzahl Texte' ersetzen

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "plt.ylabel('Wie oft die Anzahl vorkommt')\n",
Anzahl Texte

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "sns.histplot(data, x='Anzahl Wörter', weights='Häufigkeit', discrete=True, binwidth=1)\n",
würde breitere Bins nehmen

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "In den Paragraphtexten kommt regelmässig \"cnn\" vor und viele allgemeine Wörter wie one, us, also und told. Dies im Gegensatz zu den Fragen und Antworten, wo auch Wörter, wie \"killed\" und \"p
würde noch sage, dass das sinn macht. Da die Antworten nicht zitieren oder nicht den Namen der Zeitung beinhalten.

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "Die meisten Wörter kommen nur sehr selten vor. Die Testwörter, welche nicht in den bestehenden Embeddings sind, werden vom Modell nicht verstanden. Wenn es auch im Testset viele neue Wörter hat,
Stimmt das wirklich? das würde sich ja untersuchen lassen:
- a) wieviele wörter gibt es im test-datensatz die im trainingsdatensatz nicht vorhanden sind?
- b) arbeitet das modell mit ganzen wörter als embeddings oder mehr mit wortteilen (tokens) als embeddings (ähnlich wie ChatGPT: [https://platform.openai.com/tokenizer](https://platform.openai.com/tokenizer))

2024-01-03 22:02 UTC, florinbarbisch commented on report.ipynb
> +    "sns.kdeplot(values2, bw_adjust=0.5, fill=True)\n",
würde eine log-skalierung der y-Achse mehr Überblick und Erkenntnisse schaffen?

2024-01-04 09:38 UTC, swiggy123 commented on report.ipynb
> +    "Die Texte haben eine sehr stark unterschiedliche Anzahl von Fragen und Antworten. Dies könnte bei den Texten, welche wenige Fragen und Antworten haben, zu Overfitting führen."
Wer das e möglichi Antwort?

Die Texte haben eine stark unterschiedliche Anzahl von Fragen und Antworten. Dies könnte bei den Texten, welche wenige Fragen und Antworten haben, dazu führen, dass das Modell die Fragen und Antworten schneller lernt und somit zu Overfitting führen könnte.

2024-01-04 09:47 UTC, swiggy123 commented on report.ipynb
> +    "sns.kdeplot(values2, bw_adjust=0.5, fill=True)\n",
Wenn, dann von der x-achse (können wir noch zusammen anschauen...)

2024-01-04 10:33 UTC, swiggy123 commented on report.ipynb
> +    "Die meisten Wörter kommen nur sehr selten vor. Die Testwörter, welche nicht in den bestehenden Embeddings sind, werden vom Modell nicht verstanden. Wenn es auch im Testset viele neue Wörter hat,
Ha jetzt das auno ergänzt, aber es wer viellicht nid schlecht, wenn mir das auno ahluege...

2024-01-04 12:56 UTC, florinbarbisch commented on report.ipynb
> +    "Die Texte haben eine sehr stark unterschiedliche Anzahl von Fragen und Antworten. Dies könnte bei den Texten, welche wenige Fragen und Antworten haben, zu Overfitting führen."
Ja das passt👍🏻

2024-01-04 12:57 UTC, florinbarbisch commented on report.ipynb
> +    "Die meisten Wörter kommen nur sehr selten vor. Die Testwörter, welche nicht in den bestehenden Embeddings sind, werden vom Modell nicht verstanden. Wenn es auch im Testset viele neue Wörter hat,
klar, mache mir morn

2024-01-05 15:15 UTC, florinbarbisch approved these changes

2024-01-05 15:23 UTC, merged